
module = file_server
ext_cflag = -DASCS_SERVER_PORT=5050 -DASCS_RESTORE_OBJECT -DASCS_WANT_MSG_SEND_NOTIFY -DASCS_INPUT_QUEUE=non_lock_queue
ext_cflag += -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE

include ../config.mk

